name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # installs Imports + Suggests from DESCRIPTION for an R CMD check
          extra-packages: any::rcmdcheck
          needs: check

      # (optional) sanity check so you see it in the logs
      - name: Confirm locpol is installed
        run: Rscript -e 'print(packageVersion("locpol"))'

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true