name: test-coverage

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R (use binaries)
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install deps (cached)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          extra-packages: |
            any::covr
            any::testthat

      - name: Run test coverage and upload to Codecov
        run: Rscript -e 'covr::codecov()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # For private repos, also set CODECOV_TOKEN in repo secrets and uncomment:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

